import { Majors } from "@/types";
import { NextResponse } from "next/server";

const majors = {
  "Aristotle University of Thessaloniki": {
    Math: "Department of Mathematics",
    Phys: "Department of Physics",
    Chem: "Department of Chemistry",
    Bio: "Department of Biology",
    Geol: "Department of Geology",
    Info: "Department of Informatics",
    ECE: "Department of Electrical and Computer Engineering",
    ME: "Department of Mechanical Engineering",
    ArchE: "Department of Architecture Engineering",
    CivilE: "Department of Civil Engineering",
    ChemE: "Department of Chemical Engineering",
    AgroSurveyE: "Department of Agronomics and Surveying Engineering",
    SpatialE: "Department of Spatial Planning and Development Engineering",
    Phil: "Department of Philology",
    HistArch: "Department of History and Archaeology",
    PhilPed: "Department of Philosophy and Pedagogy",
    EngLit: "Department of English Language and Literature",
    FrenchLit: "Department of French Language and Literature",
    GermanLit: "Department of German Language and Literature",
    ItalianLit: "Department of Italian Language and Literature",
    Psych: "Department of Psychology",
    Med: "Department of Medicine",
    Pharm: "Department of Pharmacy",
    Dent: "Department of Dentistry",
    VetMed: "Department of Veterinary Medicine",
    Law: "Department of Law",
    Agri: "Department of Agriculture",
    Forestry: "Department of Forestry and Natural Environment",
    PrimaryEd: "Department of Primary Education Pedagogy",
  },
  "National and Kapodistrian University of Athens": {
    Math: "Department of Mathematics",
    Phys: "Department of Physics",
    Chem: "Department of Chemistry",
    Bio: "Department of Biology",
    Geol: "Department of Geology and Environmental Science",
    Info: "Department of Informatics and Telecommunications",
    Hist: "Department of History and Philosophy of Science",
    DIT: "Department of Digital Industry Technologies",
    Astro: "Department of Aerospace Science and Technology",
    Phil: "Department of Philology",
    HistArch: "Department of History and Archaeology",
    Philos: "Department of Philosophy",
    SecEd: "Department of Secondary Education Pedagogy",
    EngLit: "Department of English Language and Literature",
    FrenchLit: "Department of French Language and Literature",
    GermanLit: "Department of German Language and Literature",
    ItalianLit: "Department of Italian Language and Literature",
    SpanishLit: "Department of Spanish Language and Literature",
    RussSlavic:
      "Department of Russian Language and Literature and Slavic Studies",
    Theatre: "Department of Theatre Studies",
    Music: "Department of Music Studies",
    Psych: "Department of Psychology",
    PhilPedPsy: "Department of Philosophy - Pedagogy and Psychology",
    EngArchHist:
      "English-language undergraduate program in Archaeology, History and Literature of Ancient Greece",
    Med: "School of Medicine",
    Pharm: "School of Pharmacy",
    Dent: "School of Dentistry",
    Nurs: "School of Nursing",
    Law: "School of Law",
    Theo: "School of Theology",
    SocialTheoRel: "School of Social Theology and Religious Studies",
    Econ: "Department of Economics",
    PolSciPubAdmin: "Department of Political Science and Public Administration",
    TurkAsian: "Department of Turkish and Modern Asian Studies",
    CommMedia: "Department of Communication and Media Studies",
    Sociol: "Department of Sociology",
    BusAdminOrgMgmt:
      "Department of Business Administration and Organizations Management",
    PortMgmtShipping: "Department of Port Management and Shipping",
    DigArtsCinema: "Department of Digital Arts and Cinema",
    PrimaryEd: "School of Primary Education Pedagogy",
    EarlyChild: "Department of Education and Training in Early Childhood",
    PhysEdSport: "Department of Physical Education and Sports Science",
    RuralDevAgriFood:
      "Department of Rural Development, Agri-food and Natural Resource Management",
  },
  "National Technical University of Athens": {
    CivilEng: "Department of Civil Engineering",
    MechEng: "Department of Mechanical Engineering",
    ElecCompEng: "Department of Electrical and Computer Engineering",
    ChemEng: "Department of Chemical Engineering",
    ArchEng: "Department of Architecture Engineering",
    AgrSurEng: "Department of Agricultural and Surveying Engineering",
    NavArchMarEng: "Department of Naval Architects and Marine Engineers",
    MiningEng: "Department of Mining and Metallurgical Engineering",
    AppMathPhys: "Department of Applied Mathematics and Physical Sciences",
  },
  "University of Patras": {
    EduSciPreSchAge:
      "Department of Educational Sciences and Early Childhood Education",
    EduSciSocWork: "Department of Educational Sciences and Social Work",
    TheatreStudies: "Department of Theatre Studies",
    Philology: "Department of Philology",
    Philosophy: "Department of Philosophy",
    HistoryArchaeology: "Department of History and Archaeology",
    Agriculture: "Department of Agriculture",
    FoodSciTech: "Department of Food Science and Technology",
    FisheriesAquaculture: "Department of Fisheries and Aquaculture",
    SustainableAgri: "Department of Sustainable Agriculture",
    SpeechTherapy: "Department of Speech Therapy",
    Nursing: "Department of Nursing",
    Physiotherapy: "Department of Physiotherapy",
    Medicine: "Department of Medicine",
    Pharmacy: "Department of Pharmacy",
    Mathematics: "Department of Mathematics",
    Physics: "Department of Physics",
    Chemistry: "Department of Chemistry",
    Biology: "Department of Biology",
    Geology: "Department of Geology",
    MaterialsSci: "Department of Materials Science",
    BusinessAdmin: "Department of Business Administration",
    TourismAdmin: "Department of Tourism Administration",
    AdminScienceTech: "Department of Administrative Science and Technology",
    Economics: "Department of Economics",
    ElectrEngCompSci:
      "Department of Electrical Engineering and Computer Science",
    MechAeroEng: "Department of Mechanical and Aeronautical Engineering",
    CivilEng: "Department of Civil Engineering",
    ChemEng: "Department of Chemical Engineering",
    CompEngInfoTech: "Department of Computer Engineering and Informatics",
    ArchEng: "Department of Architecture Engineering",
  },
  "University of Crete": {
    Philology: "Department of Philology",
    HistoryArchaeology: "Department of History and Archaeology",
    Philosophy: "Department of Philosophy",
    Sociology: "Department of Sociology",
    Psychology: "Department of Psychology",
    Economics: "Department of Economics",
    PoliticalScience: "Department of Political Science",
    PrimaryEducationPedagogy: "Department of Primary Education Pedagogy",
    PreschoolEducationPedagogy: "Department of Preschool Education Pedagogy",
    Mathematics: "Department of Mathematics",
    Physics: "Department of Physics",
    Chemistry: "Department of Chemistry",
    Biology: "Department of Biology",
    Medicine: "Department of Medicine",
  },
  "University of Thessaly": {
    PreschoolEducation: "Department of Preschool Education",
    PrimaryEducation: "Department of Primary Education",
    SpecialEducation: "Department of Special Education",
    HistoryArchaeologyAnthropology:
      "Department of History, Archaeology, and Social Anthropology",
    LinguisticsInterculturalStudies:
      "Department of Linguistics and Intercultural Studies",
    CultureCreativeMediaIndustries:
      "Department of Culture and Creative Media Industries",
    SpatialPlanningUrbanRegionalDevelopment:
      "Department of Spatial Planning, Urban and Regional Development",
    MechanicalEngineering: "Department of Mechanical Engineering",
    CivilEngineering: "Department of Civil Engineering",
    ElectricalEngineeringComputerScience:
      "Department of Electrical Engineering and Computer Science",
    Medicine: "Department of Medicine",
    BiochemistryBiotechnology: "Department of Biochemistry and Biotechnology",
    Nursing: "Department of Nursing",
    VeterinaryMedicine: "Department of Veterinary Medicine",
    PublicUnifiedHealth: "Department of Public and Unified Health",
    Physiotherapy: "Department of Physiotherapy",
    AgriculturePlantProductionRuralEnvironment:
      "Department of Agriculture, Plant Production, and Rural Environment",
    AgricultureFisheriesAquaticEnvironment:
      "Department of Agriculture, Fisheries, and Aquatic Environment",
    AgricultureAgrotechnology: "Department of Agriculture - Agrotechnology",
    AnimalScience: "Department of Animal Science",
    FoodScienceNutrition: "Department of Food Science and Nutrition",
    AccountingFinance: "Department of Accounting and Finance",
    BusinessAdministration: "Department of Business Administration",
    Economics: "Department of Economics",
    DigitalSystems: "Department of Digital Systems",
    EnergySystems: "Department of Energy Systems",
    Environment: "Department of Environment",
    ForestryWoodScienceDesign:
      "Department of Forestry, Wood Science, and Design",
    ComputerScienceTelecommunications:
      "Department of Computer Science and Telecommunications",
    ComputerScienceBiomedicalApplications:
      "Department of Computer Science with Applications in Biomedicine",
    Mathematics: "Department of Mathematics",
    Physics: "Department of Physics",
    PhysicalEducationSportsScience:
      "Department of Physical Education and Sports Science",
    DieteticsNutrition: "Department of Dietetics and Nutrition",
  },
  "University of Aegean": {
    Geography: "Department of Geography",
    SocialAnthropologyHistory: "Department of Social Anthropology and History",
    Sociology: "Department of Sociology",
    CulturalTechnologyCommunication:
      "Department of Cultural Technology and Communication",
    Environment: "Department of Environment",
    OceanographyMarineSciences:
      "Department of Oceanography and Marine Sciences",
    FoodScienceNutrition: "Department of Food Science and Nutrition",
    BusinessAdministration: "Department of Business Administration",
    MaritimeStudiesBusinessServices:
      "Department of Maritime Studies and Business Services",
    TourismEconomicsManagement:
      "Department of Tourism Economics and Management",
    EconomicEngineeringManagement:
      "Department of Economic Engineering and Management",
    InformationCommunicationSystemsEngineering:
      "Department of Information and Communication Systems Engineering",
    ProductSystemsDesignEngineering:
      "Department of Product and Systems Design Engineering",
    Mathematics: "Department of Mathematics",
    StatisticsActuarialFinancialMathematics:
      "Department of Statistics and Actuarial-Financial Mathematics",
    PrimaryEducation: "Department of Primary Education",
    PreschoolEducationEducationalDesign:
      "Department of Preschool Education and Educational Design",
    MediterraneanStudies: "Department of Mediterranean Studies",
  },
  "Athens University of Economics and Business": {
    BusinessOrganizationManagement:
      "Department of Business Organization and Management",
    MarketingCommunication: "Department of Marketing and Communication",
    AccountingFinance: "Department of Accounting and Finance",
    BusinessAdministrationTechnology:
      "Department of Business Administration and Technology",
    EconomicScience: "Department of Economic Science",
    InternationalEuropeanEconomicStudies:
      "Department of International and European Economic Studies",
    Informatics: "Department of Informatics",
    Statistics: "Department of Statistics",
  },
  "University of Ioannina": {
    Philology: "Department of Philology",
    HistoryArchaeology: "Department of History and Archaeology",
    Philosophy: "Department of Philosophy",
    Mathematics: "Department of Mathematics",
    Physics: "Department of Physics",
    Chemistry: "Department of Chemistry",
    Medicine: "Department of Medicine",
    BiologicalApplicationsTechnologies:
      "Department of Biological Applications and Technologies",
    Nursing: "Department of Nursing",
    SpeechTherapy: "Department of Speech Therapy",
    ComputerEngineeringInformatics:
      "Department of Computer Engineering and Informatics",
    MaterialsScienceEngineering: "Department of Materials Science Engineering",
    ArchitectureEngineering: "Department of Architecture Engineering",
    PrimaryEducation: "Department of Primary Education",
    PreschoolEducation: "Department of Preschool Education",
    EconomicScience: "Department of Economic Science",
    AccountingFinancialManagementPreveza:
      "Department of Accounting and Financial Management - Preveza",
    EarlyChildhoodEducationCare:
      "Department of Early Childhood Education and Care",
    Psychology: "Department of Psychology",
    FineArtsArtSciences: "Department of Fine Arts and Art Sciences",
    MusicStudies: "Department of Music Studies",
    Agriculture: "Department of Agriculture",
    InformaticsTelecommunications:
      "Department of Informatics and Telecommunications",
  },
  "International Hellenic University": {
    BusinessAdministration: "Department of Business Administration",
    EconomicScience: "Department of Economic Science",
    SupplyChainManagement: "Department of Supply Chain Management",
    OrganizationalManagementMarketingTourism:
      "Department of Organizational Management, Marketing, and Tourism",
    AccountingInformaticsSystems:
      "Department of Accounting, Informatics, and Systems",
    LibraryArchivalInformationSystems:
      "Department of Library, Archival, and Information Systems",
    EarlyChildhoodEducationCare:
      "Department of Early Childhood Education and Care",
    BiomedicalSciences: "Department of Biomedical Sciences",
    NutritionDieteticsScience: "Department of Nutrition and Dietetics Science",
    Midwifery: "Department of Midwifery",
    PhysicalTherapy: "Department of Physical Therapy",
    Nursing: "Department of Nursing",
    MechanicalEngineering: "Department of Mechanical Engineering",
    Geoinformatics: "Department of Geoinformatics",
    CivilEngineering: "Department of Civil Engineering",
    ComputerEngineeringInformaticsTelecommunications:
      "Department of Computer Engineering, Informatics, and Telecommunications",
    EnvironmentalEngineering: "Department of Environmental Engineering",
    ProductionManagementEngineering:
      "Department of Production Management Engineering",
    ComputerScienceElectronicSystems:
      "Department of Computer Science and Electronic Systems",
    InteriorArchitecture: "Department of Interior Architecture",
    CreativeDesignClothing: "Department of Creative Design and Clothing",
    FoodScienceTechnology: "Department of Food Science and Technology",
    Agriculture: "Department of Agriculture",
  },
  "University of West Attica": {
    EE: "Department of Electrical and Electronic Engineering",
    BME: "Department of Biomedical Engineering",
    IDPE: "Department of Industrial Design and Production Engineering",
    CEI: "Department of Computer Engineering and Informatics",
    SGE: "Department of Surveying and Geoinformatics Engineering",
    ME: "Department of Mechanical Engineering",
    NAME: "Department of Naval Architecture and Marine Engineering",
    CE: "Department of Civil Engineering",
    BS: "Department of Biomedical Sciences",
    OT: "Department of Occupational Therapy",
    Midwifery: "Department of Midwifery",
    Nursing: "Department of Nursing",
    Physiotherapy: "Department of Physiotherapy",
    ALIS: "Department of Archival, Library and Information Systems",
    BA: "Department of Business Administration",
    Tourism: "Department of Tourism Management",
    SocialWork: "Department of Social Work",
    Accounting: "Department of Accounting and Finance",
    ECEC: "Department of Early Childhood Education and Care",
    PublicHealth: "Department of Public Health Policy",
    CommunityHealth: "Department of Public and Community Health",
    FoodScience: "Department of Food Science and Technology",
    WineScience: "Department of Wine, Vine and Beverage Sciences",
    GraphicDesign: "Department of Graphic Design and Visual Communication",
    InteriorArchitecture: "Department of Interior Architecture",
    Conservation: "Department of Conservation of Antiquities and Works of Art",
    Photography: "Department of Photography and Audiovisual Arts",
  },
  "Democritus University of Thrace": {
    Law: "Department of Law",
    PhysicalEducationSportsScience:
      "Department of Physical Education and Sports Science",
    OccupationalTherapy: "Department of Occupational Therapy",
    HistoryEthnology: "Department of History and Ethnology",
    GreekPhilology: "Department of Greek Philology",
    LanguageLiteratureCultureBorderingCountries:
      "Department of Language, Literature, and Culture of Bordering Countries",
    SocialWork: "Department of Social Work",
    SocialPolicy: "Department of Social Policy",
    Economics: "Department of Economics",
    PoliticalScience: "Department of Political Science",
    CivilEngineering: "Department of Civil Engineering",
    ElectricalEngineeringComputerEngineering:
      "Department of Electrical and Computer Engineering",
    EnvironmentalEngineering: "Department of Environmental Engineering",
    Architecture: "Department of Architecture",
    ProductionEngineeringManagement:
      "Department of Production Engineering and Management",
    Medicine: "Department of Medicine",
    MolecularBiologyGenetics: "Department of Molecular Biology and Genetics",
    Nursing: "Department of Nursing",
    PreschoolEducation: "Department of Preschool Education",
    ForestryManagementEnvironmentNaturalResources:
      "Department of Forestry Management, Environmental Science, and Natural Resources",
    RuralDevelopment: "Department of Rural Development",
    ViticultureOenology: "Department of Viticulture and Oenology",
    NaturalEnvironmentClimateResilience:
      "Department of Natural Environment and Climate Resilience",
    ComputerScience: "Department of Computer Science",
    Physics: "Department of Physics",
    Chemistry: "Department of Chemistry",
    ManagementScienceTechnology:
      "Department of Management Science and Technology",
    AccountingFinance: "Department of Accounting and Finance",
  },
  "University of Macedonia": {
    BusinessAdministration: "Department of Business Administration",
    AccountingFinance: "Department of Accounting and Finance",
    Economics: "Department of Economics",
    BalkanSlavicEasternStudies:
      "Department of Balkan, Slavic, and Eastern Studies",
    InternationalEuropeanStudies:
      "Department of International and European Studies",
    EducationalSocialPolicy: "Department of Educational and Social Policy",
    MusicScienceArt: "Department of Music Science and Art",
    AppliedInformatics: "Department of Applied Informatics",
  },
  "University of Piraeus": {
    Economics: "Department of Economics",
    BusinessAdministration: "Department of Business Administration",
    InternationalEuropeanStudies:
      "Department of International and European Studies",
    TourismStudies: "Department of Tourism Studies",
    MaritimeStudies: "Department of Maritime Studies",
    IndustrialManagementTechnology:
      "Department of Industrial Management and Technology",
    FinancialBankingManagement:
      "Department of Financial and Banking Management",
    StatisticsInsuranceScience:
      "Department of Statistics and Insurance Science",
    Informatics: "Department of Informatics",
    DigitalSystems: "Department of Digital Systems",
  },
  "Technical University of Crete": {
    MPD: "School of Production Engineering and Management",
    MINM: "School of Mineral Resources Engineering",
    ECE: "School of Electrical and Computer Engineering",
    CME: "School of Chemical and Environmental Engineering",
    ARCH: "School of Architectural Engineering",
  },
  "University of Western Macedonia": {
    EEECS: "Department of Electrical and Computer Engineering",
    MechEng: "Department of Mechanical Engineering",
    MMP: "Department of Mineral Resources Engineering",
    PDPS: "Department of Product and Systems Design Engineering",
    ChemEng: "Department of Chemical Engineering",
    DMST: "Department of Business Administration and Technology",
    LFA: "Department of Accounting and Financial Management",
    OBE: "Department of Business Administration",
    SSS: "Department of Statistics and Insurance Science ",
    Econ: "Department of Economics",
    IES: "Department of International and European Studies ",
    Math: "Department of Mathematics",
    CS: "Department of Computer Science",
    OT: "Department of Occupational Therapy",
    Midwifery: "Department of Midwifery",
    Agri: "Department of Agriculture",
    PEDFlorina: "Department of Primary Education ",
    PEDN: "Department of Preschool Education ",
    Psych: "Department of Psychology",
    CM: "Department of Communication and Digital Media",
    FAA: "Department of Fine and Applied Arts",
  },
  "University of Peloponnese": {
    Econ: "Department of Economics",
    CS: "Department of Computer Science and Telecommunications",
    DS: "Department of Digital Systems",
    DMST: "Department of Business Administration and Technology",
    HAAM: "Department of History, Archaeology, and Management of Cultural Heritage",
    Phil: "Department of Philology",
    CEEP: "Department of Social and Educational Policy",
    PEIR: "Department of Political Science and International Relations",
    TS: "Department of Theatre Studies",
    SM: "Department of Sports Management",
    FST: "Department of Food Science and Technology",
    Agri: "Department of Agriculture",
    BAM: "Department of Business Administration and Management",
    LMFM: "Department of Accounting and Financial Management",
    Nursing: "Department of Nursing",
    Physio: "Department of Physiotherapy",
    SLT: "Department of Speech and Language Therapy ",
    NDT: "Department of Nutrition and Dietetics",
    EECE: "Department of Electrical and Computer Engineering",
    MechEng: "Department of Mechanical Engineering",
    CivilEng: "Department of Civil Engineering",
  },
  "Ionian University": {
    RD: "Department of Regional Development",
    Tourism: "Department of Tourism",
    "Environmental Studies": "Department of Environmental Studies",
    "Food Science and Technology": "Department of Food Science and Technology",
    "Audio and Visual Arts": "Department of Audio and Visual Arts",
    "Music Studies": "Department of Music Studies",
    Ethnomusicology: "Department of Ethnomusicology",
    "Archival, Library and Museum Studies":
      "Department of Archival, Library and Museum Studies",
    "Computer Science": "Department of Computer Science",
    "Digital Media and Communication":
      "Department of Digital Media and Communication",
    History: "Department of History",
    "Foreign Languages, Translation and Interpretation":
      "Department of Foreign Languages, Translation and Interpretation",
  },
  "Hellenic Mediterranean University": {
    ECE: "Department of Electrical and Computer Engineering",
    ME: "Department of Mechanical Engineering",
    EE: "Department of Electronic Engineering",
    BAT: "Department of Business Administration & Tourism",
    MST: "Department of Management Science and Technology",
    AF: "Department of Accounting and Finance",
    MTA: "Department of Music Technology and Acoustics",
    Nursing: "Department of Nursing",
    SW: "Department of Social Work",
    NDS: "Department of Nutrition and Dietetics Sciences",
    Agri: "Department of Agriculture",
  },
  "Agricultural University of Athens": {
    CS: "Department of Crop Science",
    AS: "Department of Animal Science and Aquaculture",
    NRMAE:
      "Department of Natural Resources Management and Agricultural Engineering",
    Biotech: "Department of Biotechnology",
    FSHN: "Department of Food Science and Human Nutrition",
    AE: "Department of Agricultural Economics and Rural Development",
    ECE: "Department of Electrical and Computer Engineering",
    ME: "Department of Mechanical Engineering",
    EE: "Department of Electronic Engineering",
    BAT: "Department of Business Administration & Tourism",
    MST: "Department of Management Science and Technology",
    AF: "Department of Accounting and Finance",
    MTA: "Department of Music Technology and Acoustics",
    Nursing: "Department of Nursing",
    SW: "Department of Social Work",
    NDS: "Department of Nutrition and Dietetics Sciences",
    Agri: "Department of Agriculture",
  },
  "Panteion University": {
    PAD: "Department of Public Administration",
    EEPAD: "Department of Economics and Regional Development",
    PPEH: "Department of Political Science and History",
    CWP: "Department of Social Policy",
    CS: "Department of Sociology",
    SAA: "Department of Social Anthropology",
    Psy: "Department of Psychology",
    IEPRS: "Department of International, European and Regional Studies",
    CMP: "Department of Communication, Media and Culture",
  },
  "Harokopio University": {
    EASD: "Department of Economics and Sustainable Development",
    GEO: "Department of Geography",
    NSD: "Department of Nutrition and Dietetics Science",
    CIT: "Department of Computer Science and Telecommunications",
  },
  "Athens School of Fine Arts": {
    FA: "Department of Fine Arts",
    THA: "Department of Theory and History of Art",
  },
};

export async function GET() {
  return NextResponse.json(majors);
}
